### PR TITLE
Add css for tabs component

### PR DESCRIPTION
**Pull request by ThijmenKort**

### CODE REVIEW

**Comment by tabatii** [comment]
can you please add the same css to this class too `.fi-tabs` ?

**Comment by ThijmenKort** [comment]
> can you please modify the PR and add the same css to this class too `.fi-tabs` ?

For which component is that?

**Comment by ThijmenKort** [comment]
image
Border is too thick with current code. Changing it to ring-2 works but doesn't seem right. Not sure what the correct fix is.

Above is newly added code. Below is already existing.

**Comment by Hasnayeen** [comment]
@ThijmenKort can you share some UI screenshot about the changes this PR make please?

**Comment by ThijmenKort** [comment]
@Hasnayeen below are before and after. Like i said, the border is too thick but i am not sure what i need to add to fix that because the code is the same as all other ones.
image
image

**Comment by Hasnayeen** [comment]
does `ring-1` not work?

**Comment by ThijmenKort** [comment]
> does `ring-1` not work?

It works but then but the other ones like .fi-ta-ctn use ring-2.

**Comment by Hasnayeen** [comment]
if it works then use `ring-1`, doesn't have to be same as `fi-ta-ctn`. 
also compile the css `THEME=sunset npm run build:styles`

**Pull request merged**
