### PR TITLE
Add support laravel 11, and add test for php 8.3

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by lloricode** [comment]
⚗️ Using this package? If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add my fork to the `repositories` property of your `composer.json`:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/lloricode/themes.git"
        }
    ]
}
```
Then update your dependency constraint to reference this branch:
```json
{
    "require": {
         "hasnayeen/themes": "dev-feature/laravel-11",
    }
}
```
Finally, run: `composer update`

**Comment by Hasnayeen** [comment]
tested on a fresh L11, works! thanks for the PR :+1:

**Comment by lloricode** [comment]
> tested on a fresh L11, works! thanks for the PR :+1: 

Hi, can you release a tag for it?

**Comment by Hasnayeen** [comment]
> > tested on a fresh L11, works! thanks for the PR 👍
> 
> Hi, can you release a tag for it?

Done!

**Comment by lloricode** [comment]
> > > tested on a fresh L11, works! thanks for the PR 👍
> > 
> > 
> > Hi, can you release a tag for it?
> 
> Done!

thank you

**Pull request merged**
